{% set name = "harissa" %}
{% set version = "3.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13739bfcaa04618fad29db2766aa0f9f24641b51170355fe056490c7e7365dd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - scipy >=1.7
    - numba >=0.55
    - matplotlib-base >=3.4
    - networkx >=2.6

test:
  imports:
    - harissa
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/harissa-framework/harissa
  doc_url: https://harissa-framework.github.io/harissa
  summary: Simulation and inference of gene regulatory networks based on transcriptional bursting
  description: |
    Integrated set of tools to perform mechanistic simulation and inference
    of gene regulatory networks from single-cell data, based on stochastic
    gene expression driven by the transcriptional bursting phenomenon.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ulysseherbach
    - nseyler1
